services:
  angular-frontend:
    container_name: Frontend
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always   

  myapp-backend:
    container_name: Backend
    build: ./backend
    networks:
      - app-network
    restart: always  
    ports:
      - "8080:8080" 

networks:
  app-network:
    driver: bridge
